# Generated by Django 3.2.5 on 2021-08-10 11:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='nome da área')),
                ('validado', models.BooleanField(default=False, verbose_name='esta área foi validada?')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='geom')),
            ],
        ),
    ]
